spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/diplom
    username: admin_diplom
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    contexts: dev
    change-log: 
      classpath:db/changelog/db.changelog-master.xml
      
init:
  title: DevPub
  subtitle: Developer's Stories
  phone: +7 999 516 80-45
  email: afanasevek@gmail.com
  copyright: Afanasev Evgeny
  copyrightFrom: 2020